[22:24:24.384] [31mERROR[39m:
    status: 500
    detail: "An unexpected error occurred on node_modules\sequelize\lib\dialects\mysql\query.js - related to database, external services etc."
    source: {
      "functionName": "Query.run",
      "fileName": "node_modules\sequelize\lib\dialects\mysql\query.js",
      "lineNumber": 52
    }
    build_info: "18.18.0"
    commitHash: "6bed6f18268395d7fd7f04ea7134994b7ffb8ea1"
    requestId: "23f08685-cc60-4c4f-99cb-e27e3430a6a1"
    stack: "Error\n    at Query.run (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)\n    at D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\sequelize.js:315:28\n    at async MySQLQueryInterface.insert (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)\n    at async Photo.save (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:2490:35)\n    at async photo.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:1362:12)\n    at async store (D:\GithubRepositorios\conexao095_xrlab_backend\src\controllers\photo.js:21:19)"
[22:25:53.069] [31mERROR[39m:
    status: 400
    detail: "The fields 'longitude' contain invalid values."
    source: {
      "functionName": "InstanceValidator._validate",
      "fileName": "node_modules\sequelize\lib\instance-validator.js",
      "lineNumber": 50
    }
    build_info: "18.18.0"
    commitHash: "6bed6f18268395d7fd7f04ea7134994b7ffb8ea1"
    requestId: "a462bb3e-1a5f-42c0-bdea-3f1b2caf23db"
    stack: "SequelizeValidationError: Validation error: 'longitude' is required.\n    at InstanceValidator._validate (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\instance-validator.js:60:7)\n    at async InstanceValidator.validate (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\instance-validator.js:54:12)\n    at async Photo.save (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:2426:7)\n    at async photo.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:1362:12)\n    at async store (D:\GithubRepositorios\conexao095_xrlab_backend\src\controllers\photo.js:21:19)"
[22:25:55.488] [31mERROR[39m:
    status: 500
    detail: "An unexpected error occurred on node_modules\sequelize\lib\dialects\mysql\query.js - related to database, external services etc."
    source: {
      "functionName": "Query.run",
      "fileName": "node_modules\sequelize\lib\dialects\mysql\query.js",
      "lineNumber": 52
    }
    build_info: "18.18.0"
    commitHash: "6bed6f18268395d7fd7f04ea7134994b7ffb8ea1"
    requestId: "72e8f928-feee-4e4b-b984-dc10dcae3e8a"
    stack: "Error\n    at Query.run (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)\n    at D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\sequelize.js:315:28\n    at async MySQLQueryInterface.insert (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)\n    at async Photo.save (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:2490:35)\n    at async photo.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:1362:12)\n    at async store (D:\GithubRepositorios\conexao095_xrlab_backend\src\controllers\photo.js:21:19)"
[22:28:50.620] [31mERROR[39m:
    status: 500
    detail: "An unexpected error occurred on node_modules\sequelize\lib\dialects\mysql\query.js - related to database, external services etc."
    source: {
      "functionName": "Query.run",
      "fileName": "node_modules\sequelize\lib\dialects\mysql\query.js",
      "lineNumber": 52
    }
    build_info: "18.18.0"
    commitHash: "6bed6f18268395d7fd7f04ea7134994b7ffb8ea1"
    requestId: "73ca24c2-2820-4391-a5bd-cdaabd8dd869"
    stack: "Error\n    at Query.run (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)\n    at D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\sequelize.js:315:28\n    at async MySQLQueryInterface.insert (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)\n    at async Photo.save (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:2490:35)\n    at async photo.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:1362:12)\n    at async store (D:\GithubRepositorios\conexao095_xrlab_backend\src\controllers\photo.js:21:19)"
[22:30:20.739] [31mERROR[39m:
    status: 500
    detail: "An unexpected error occurred on node_modules\sequelize\lib\dialects\mysql\query.js - related to database, external services etc."
    source: {
      "functionName": "Query.run",
      "fileName": "node_modules\sequelize\lib\dialects\mysql\query.js",
      "lineNumber": 52
    }
    build_info: "18.18.0"
    commitHash: "6bed6f18268395d7fd7f04ea7134994b7ffb8ea1"
    requestId: "240d3f99-04fc-4da8-85ae-16a8f5975e69"
    stack: "Error\n    at Query.run (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\mysql\query.js:52:25)\n    at D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\sequelize.js:315:28\n    at async MySQLQueryInterface.insert (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:21)\n    at async Photo.save (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:2490:35)\n    at async photo.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:1362:12)\n    at async store (D:\GithubRepositorios\conexao095_xrlab_backend\src\controllers\photo.js:21:19)"
[22:33:30.880] [31mERROR[39m:
    status: 400
    detail: "The fields 'longitude' contain invalid values."
    source: {
      "functionName": "InstanceValidator._validate",
      "fileName": "node_modules\sequelize\lib\instance-validator.js",
      "lineNumber": 50
    }
    build_info: "18.18.0"
    commitHash: "6bed6f18268395d7fd7f04ea7134994b7ffb8ea1"
    requestId: "a26ea69d-df84-4c6f-9430-d812f5870ad0"
    stack: "SequelizeValidationError: Validation error: 'longitude' is required.\n    at InstanceValidator._validate (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\instance-validator.js:50:13)\n    at async InstanceValidator._validateAndRunHooks (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\instance-validator.js:60:7)\n    at async InstanceValidator.validate (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\instance-validator.js:54:12)\n    at async Photo.save (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:2426:7)\n    at async photo.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\model.js:1362:12)\n    at async HasMany.create (D:\GithubRepositorios\conexao095_xrlab_backend\node_modules\sequelize\lib\associations\has-many.js:301:12)\n    at async store (D:\GithubRepositorios\conexao095_xrlab_backend\src\controllers\photo.js:21:19)"
